title: Skylar MacDonald
author: Skylar MacDonald
email: contact@skylar.tel
description: Reluctant technologist. CAD & Technical Lead/nerd at London Ambulance Service. Tech stuff, NHS/999 stuff, occasional Excel witchcraft. Views, regrettably, my own.
baseurl: ""
url: "https://skye.fyi"

# Author
author:
  name: Skylar MacDonald
  email: contact@skylar.tel
  url: https://skye.fyi

social:
  mastodon: https://tilde.zone/@skylar
  bluesky: https://bsky.app/profile/skye.fyi
  twitter: https://twitter.com/LASSkylar

# Build settings
remote_theme: inelaah/rain
plugins:
  - jekyll-feed
# Related posts settings
related_posts_section:
  max_count: 5
  min_common_tags: 1
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
permalink: /:year/:month/:title
paginate: 5
collections:
  talks:
    output: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: Skylar MacDonald
  - scope:
      path: ""
      type: talks
    values:
      layout: talks

