title: Skylar MacDonald
author: Skylar MacDonald
email: skylar@skylarmacdonald.com
description: >
  I'm from London, UK and I do things in telly and radio.
  I also make bots and build websites sometimes.
baseurl: ""
url: ""
twitter_username: skylarmacdonald
github_username:  skylarmacdonald

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: Skylar MacDonald
